local ItemData = {
	[1] = {Name = "Sword", ItemType = 1, SubType = "Longsword"},
	[2] = {Name = "Wood", ItemType = 3, SubType = "Material"},
	[3] = {Name = "Sugoi Mushroom", ItemType = 2, SubType = "Food"},
	[4] = {Name = "Common Upgrade Crystal", ItemType = 2, SubType = "Upgrader"},
	[5] = {Name = "Steel", ItemType = 3, SubType = "Material"},
	[6] = {Name = "Iron", ItemType = 3, SubType = "Material"},
	[7] = {Name = "Steel Sword", ItemType = 1, SubType = "Longsword"},
	[8] = {Name = "Enchanted Wood", ItemType = 3, SubType = "Material"},
	[9] = {Name = "Woodcutting Trinket", ItemType = 1, SubType = "Accessory"},
	[10] = {Name = "Steel Bowstring", ItemType = 1, SubType = "Bowstring"},
	[11] = {Name = "Firefly Float", ItemType = 1, SubType = "Float"},
	[12] = {Name = "Firefly Reel", ItemType = 1, SubType = "Reel"},
	[14] = {Name = "Minnow Bait", ItemType = 2, SubType = "Bait"},
	[97] = {Name = "Fireveil Arrow", ItemType = 2, SubType = "Arrow"},
	[98] = {Name = "Light Essense", ItemType = 3, SubType = "Material"},
	[99] = {Name = "Dark Essense", ItemType = 3, SubType = "Material"},
	[100] = {Name = "Purity Crystal", ItemType = 2, SubType = "Upgrader"},
	[101] = {Name = "Dark Crystal", ItemType = 2, SubType = "Upgrader"},
	[102] = {Name = "Unstable Power Crystal", ItemType = 2, SubType = "Upgrader"},
	[103] = {Name = "Reciprem Crystal", ItemType = 2, SubType = "Upgrader"},
	[104] = {Name = "Reciprism Scroll", ItemType = 2, SubType = "Upgrader"},
	[105] = {Name = "Holy Essense", ItemType = 3, SubType = "Material"},
	[106] = {Name = "Nightmare Essense", ItemType = 3, SubType = "Material"},
	[998] = {Name = "Aetheric Surge Crystal", ItemType = 2, SubType = "Upgrader"},
	[999] = {Name = "Test Scroll", ItemType = 2, SubType = "Upgrader"},
	[1000] = {Name = "Manarias", ItemType = 1, SubType = "Longsword"},
}
return ItemData
